# Generated by Django 6.0.2 on 2026-03-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='old_api_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='old_api_key_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
